[ERROR    03-12-2013 00:01:40] Uncaught exception in /websocket
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 87, in on_message
    d = {'type': 'messages_history',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 119, in chat_handler
    'text': 'Сообщение не может быть доставлено в текущую комнату'}
KeyError: u''
[ERROR    03-12-2013 00:04:04] Uncaught exception in /websocket
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 87, in on_message
    d = {'type': 'messages_history',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 118, in chat_handler
    d = {'type': 'error',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 97, in custom_write_message
    def custom_write_message(self, d, room=None):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 165, in write_message
    self.ws_connection.write_message(message, binary=binary)
AttributeError: 'NoneType' object has no attribute 'write_message'
[ERROR    03-12-2013 00:04:07] Uncaught exception in /websocket
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 87, in on_message
    d = {'type': 'messages_history',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 118, in chat_handler
    d = {'type': 'error',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 97, in custom_write_message
    def custom_write_message(self, d, room=None):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 165, in write_message
    self.ws_connection.write_message(message, binary=binary)
AttributeError: 'NoneType' object has no attribute 'write_message'
[ERROR    03-12-2013 00:05:10] Uncaught exception in /websocket
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 87, in on_message
    d = {'type': 'messages_history',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 118, in chat_handler
    d = {'type': 'error',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 97, in custom_write_message
    def custom_write_message(self, d, room=None):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 165, in write_message
    self.ws_connection.write_message(message, binary=binary)
AttributeError: 'NoneType' object has no attribute 'write_message'
[ERROR    03-12-2013 00:05:12] Uncaught exception in /websocket
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 303, in wrapper
    return callback(*args, **kwargs)
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 87, in on_message
    d = {'type': 'messages_history',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 118, in chat_handler
    d = {'type': 'error',
  File "D:\SCRIPTS\DJANGO\tornadochat\chat_app\tornadoapp.py", line 97, in custom_write_message
    def custom_write_message(self, d, room=None):
  File "C:\Python27\lib\site-packages\tornado\websocket.py", line 165, in write_message
    self.ws_connection.write_message(message, binary=binary)
AttributeError: 'NoneType' object has no attribute 'write_message'
